version: "3.3"

services:

  twitter-redis:
    networks:
      twitter-net:
    container_name: twitter-redis
    image: redis:alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "127.0.0.1:6381:6381"

  twtter-bot:
    networks:
      twitter-net:
    container_name: twitter-bot
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    depends_on:
      - twitter-redis

networks:
  twitter-net: